import { BasicResponse } from '../../type/basicResponse';
import { searchTag } from '../../type/server';

export const LOAD_SEARCH_TAGS_REQUEST = 'LOAD_SEARCH_TAGS_REQUEST';
export const LOAD_SEARCH_TAGS_SUCCESS = 'LOAD_SEARCH_TAGS_SUCCESS';
export const LOAD_SEARCH_TAGS_FAILURE = 'LOAD_SEARCH_TAGS_FAILURE';

export const ADD_SEARCH_TAG_REQUEST = 'ADD_SEARCH_TAG_REQUEST';
export const ADD_SEARCH_TAG_SUCCESS = 'ADD_SEARCH_TAG_SUCCESS';
export const ADD_SEARCH_TAG_FAILURE = 'ADD_SEARCH_TAG_FAILURE';

export const UPDATE_SEARCH_TAG_REQUEST = 'UPDATE_SEARCH_TAG_REQUEST';
export const UPDATE_SEARCH_TAG_SUCCESS = 'UPDATE_SEARCH_TAG_SUCCESS';
export const UPDATE_SEARCH_TAG_FAILURE = 'UPDATE_SEARCH_TAG_FAILURE';

export const REMOVE_SEARCH_TAG_REQUEST = 'REMOVE_SEARCH_TAG_REQUEST';
export const REMOVE_SEARCH_TAG_SUCCESS = 'REMOVE_SEARCH_TAG_SUCCESS';
export const REMOVE_SEARCH_TAG_FAILURE = 'REMOVE_SEARCH_TAG_FAILURE';

export const ONCHANGE_ADD_SEARCH_TAG = 'ONCHANGE_ADD_SEARCH_TAG';
interface ILOAD_SEARCH_TAGS_REQUEST {
  type: typeof LOAD_SEARCH_TAGS_REQUEST;
}

interface ILOAD_SEARCH_TAGS_SUCCESS {
  type: typeof LOAD_SEARCH_TAGS_SUCCESS;
  data: Array<searchTag>;
}

interface ILOAD_SEARCH_TAGS_FAILURE {
  type: typeof LOAD_SEARCH_TAGS_FAILURE;
  error: Error;
}

interface IADD_SEARCH_TAG_REQUEST {
  type: typeof ADD_SEARCH_TAG_REQUEST;
}

interface IADD_SEARCH_TAG_SUCCESS {
  type: typeof ADD_SEARCH_TAG_SUCCESS;
  data: searchTag;
}

interface IADD_SEARCH_TAG_FAILURE {
  type: typeof ADD_SEARCH_TAG_FAILURE;
  error: Error;
}

interface IUPDATE_SEARCH_TAG_REQUEST {
  type: typeof UPDATE_SEARCH_TAG_REQUEST;
}

interface IUPDATE_SEARCH_TAG_SUCCESS {
  type: typeof UPDATE_SEARCH_TAG_SUCCESS;
  seq: number;
  data: BasicResponse<searchTag>;
}

interface IUPDATE_SEARCH_TAG_FAILURE {
  type: typeof UPDATE_SEARCH_TAG_FAILURE;
  error: Error;
}
interface IREMOVE_SEARCH_TAG_REQUEST {
  type: typeof REMOVE_SEARCH_TAG_REQUEST;
}

interface IREMOVE_SEARCH_TAG_SUCCESS {
  type: typeof REMOVE_SEARCH_TAG_SUCCESS;
  data: BasicResponse<searchTag>;
}

interface IREMOVE_SEARCH_TAG_FAILURE {
  type: typeof REMOVE_SEARCH_TAG_FAILURE;
  error: Error;
}

interface IONCHANGE_ADD_SEARCH_TAG {
  type: typeof ONCHANGE_ADD_SEARCH_TAG;
  e: React.ChangeEvent<HTMLInputElement>;
  seq: number;
}

export type SearchTagActionType =
  | ILOAD_SEARCH_TAGS_REQUEST
  | ILOAD_SEARCH_TAGS_SUCCESS
  | ILOAD_SEARCH_TAGS_FAILURE
  | IADD_SEARCH_TAG_REQUEST
  | IADD_SEARCH_TAG_SUCCESS
  | IADD_SEARCH_TAG_FAILURE
  | IUPDATE_SEARCH_TAG_REQUEST
  | IUPDATE_SEARCH_TAG_SUCCESS
  | IUPDATE_SEARCH_TAG_FAILURE
  | IREMOVE_SEARCH_TAG_REQUEST
  | IREMOVE_SEARCH_TAG_SUCCESS
  | IREMOVE_SEARCH_TAG_FAILURE
  | IONCHANGE_ADD_SEARCH_TAG;
