import { searchRequirement } from '../../type/server';

export const LOAD_SEARCH_REQUIREMENTS_REQUEST =
  'LOAD_SEARCH_REQUIREMENTS_REQUEST';
export const LOAD_SEARCH_REQUIREMENTS_SUCCESS =
  'LOAD_SEARCH_REQUIREMENTS_SUCCESS';
export const LOAD_SEARCH_REQUIREMENTS_FAILURE =
  'LOAD_SEARCH_REQUIREMENTS_FAILURE';

export const ADD_SEARCH_REQUIREMENT_REQUEST = 'ADD_SEARCH_REQUIREMENT_REQUEST';
export const ADD_SEARCH_REQUIREMENT_SUCCESS = 'ADD_SEARCH_REQUIREMENT_SUCCESS';
export const ADD_SEARCH_REQUIREMENT_FAILURE = 'ADD_SEARCH_REQUIREMENT_FAILURE';

export const UPDATE_SEARCH_REQUIREMENT_REQUEST =
  'UPDATE_SEARCH_REQUIREMENT_REQUEST';
export const UPDATE_SEARCH_REQUIREMENT_SUCCESS =
  'UPDATE_SEARCH_REQUIREMENT_SUCCESS';
export const UPDATE_SEARCH_REQUIREMENT_FAILURE =
  'UPDATE_SEARCH_REQUIREMENT_FAILURE';

export const REMOVE_SEARCH_REQUIREMENT_REQUEST =
  'REMOVE_SEARCH_REQUIREMENT_REQUEST';
export const REMOVE_SEARCH_REQUIREMENT_SUCCESS =
  'REMOVE_SEARCH_REQUIREMENT_SUCCESS';
export const REMOVE_SEARCH_REQUIREMENT_FAILURE =
  'REMOVE_SEARCH_REQUIREMENT_FAILURE';

export const ONCHANGE_ADD_SEARCH_REQUIREMENT =
  'ONCHANGE_ADD_SEARCH_REQUIREMENT';
interface ILOAD_SEARCH_REQUIREMENTS_REQUEST {
  type: typeof LOAD_SEARCH_REQUIREMENTS_REQUEST;
}

interface ILOAD_SEARCH_REQUIREMENTS_SUCCESS {
  type: typeof LOAD_SEARCH_REQUIREMENTS_SUCCESS;
  data: Array<searchRequirement>;
}

interface ILOAD_SEARCH_REQUIREMENTS_FAILURE {
  type: typeof LOAD_SEARCH_REQUIREMENTS_FAILURE;
  error: Error;
}

interface IADD_SEARCH_REQUIREMENT_REQUEST {
  type: typeof ADD_SEARCH_REQUIREMENT_REQUEST;
}

interface IADD_SEARCH_REQUIREMENT_SUCCESS {
  type: typeof ADD_SEARCH_REQUIREMENT_SUCCESS;
  data: searchRequirement;
}

interface IADD_SEARCH_REQUIREMENT_FAILURE {
  type: typeof ADD_SEARCH_REQUIREMENT_FAILURE;
  error: Error;
}

interface IUPDATE_SEARCH_REQUIREMENT_REQUEST {
  type: typeof UPDATE_SEARCH_REQUIREMENT_REQUEST;
}

interface IUPDATE_SEARCH_REQUIREMENT_SUCCESS {
  type: typeof UPDATE_SEARCH_REQUIREMENT_SUCCESS;
  seq: number;
  data: searchRequirement;
}

interface IUPDATE_SEARCH_REQUIREMENT_FAILURE {
  type: typeof UPDATE_SEARCH_REQUIREMENT_FAILURE;
  error: Error;
}
interface IREMOVE_SEARCH_REQUIREMENT_REQUEST {
  type: typeof REMOVE_SEARCH_REQUIREMENT_REQUEST;
}

interface IREMOVE_SEARCH_REQUIREMENT_SUCCESS {
  type: typeof REMOVE_SEARCH_REQUIREMENT_SUCCESS;
  data: searchRequirement;
}

interface IREMOVE_SEARCH_REQUIREMENT_FAILURE {
  type: typeof REMOVE_SEARCH_REQUIREMENT_FAILURE;
  error: Error;
}

interface IONCHANGE_ADD_SEARCH_REQUIREMENT {
  type: typeof ONCHANGE_ADD_SEARCH_REQUIREMENT;
  e: React.ChangeEvent<HTMLInputElement>;
  seq: number;
}

export type SearchRequirementActionType =
  | ILOAD_SEARCH_REQUIREMENTS_REQUEST
  | ILOAD_SEARCH_REQUIREMENTS_SUCCESS
  | ILOAD_SEARCH_REQUIREMENTS_FAILURE
  | IADD_SEARCH_REQUIREMENT_REQUEST
  | IADD_SEARCH_REQUIREMENT_SUCCESS
  | IADD_SEARCH_REQUIREMENT_FAILURE
  | IUPDATE_SEARCH_REQUIREMENT_REQUEST
  | IUPDATE_SEARCH_REQUIREMENT_SUCCESS
  | IUPDATE_SEARCH_REQUIREMENT_FAILURE
  | IREMOVE_SEARCH_REQUIREMENT_REQUEST
  | IREMOVE_SEARCH_REQUIREMENT_SUCCESS
  | IREMOVE_SEARCH_REQUIREMENT_FAILURE
  | IONCHANGE_ADD_SEARCH_REQUIREMENT;
