export const LOAD_SEARCH_REQUIREMENT_REQUEST = 'LOAD_SEARCH_REQUIREMENT_REQUEST';
export const LOAD_SEARCH_REQUIREMENT_SUCCESS = 'LOAD_SEARCH_REQUIREMENT_SUCCESS';
export const LOAD_SEARCH_REQUIREMENT_FAILURE = 'LOAD_SEARCH_REQUIREMENT_FAILURE';


interface ILOADSEARCH_REQUIREMENT_REQUEST {
    type: typeof LOAD_SEARCH_REQUIREMENT_REQUEST;
}

interface ILOADSEARCH_REQUIREMENT_SUCCESS {
    type: typeof LOAD_SEARCH_REQUIREMENT_SUCCESS;
    data: any;
}

interface ILOADSEARCH_REQUIREMENT_FAILURE {
    type: typeof LOAD_SEARCH_REQUIREMENT_FAILURE;
    error: any;
}

export type SearchRequirementActionType = ILOADSEARCH_REQUIREMENT_REQUEST | ILOADSEARCH_REQUIREMENT_SUCCESS | ILOADSEARCH_REQUIREMENT_FAILURE;