export const LOAD_SEARCH_REQUIREMENT_REQUEST =
  'LOAD_SEARCH_REQUIREMENT_REQUEST';
export const LOAD_SEARCH_REQUIREMENT_SUCCESS =
  'LOAD_SEARCH_REQUIREMENT_SUCCESS';
export const LOAD_SEARCH_REQUIREMENT_FAILURE =
  'LOAD_SEARCH_REQUIREMENT_FAILURE';

export const ADD_SEARCH_REQUIREMENT_REQUEST = 'ADD_SEARCH_REQUIREMENT_REQUEST';
export const ADD_SEARCH_REQUIREMENT_SUCCESS = 'ADD_SEARCH_REQUIREMENT_SUCCESS';
export const ADD_SEARCH_REQUIREMENT_FAILURE = 'ADD_SEARCH_REQUIREMENT_FAILURE';

interface ILOADSEARCH_REQUIREMENT_REQUEST {
  type: typeof LOAD_SEARCH_REQUIREMENT_REQUEST;
}

interface ILOADSEARCH_REQUIREMENT_SUCCESS {
  type: typeof LOAD_SEARCH_REQUIREMENT_SUCCESS;
  data: any;
}

interface ILOADSEARCH_REQUIREMENT_FAILURE {
  type: typeof LOAD_SEARCH_REQUIREMENT_FAILURE;
  error: any;
}

interface IADD_SEARCH_REQUIREMENT_REQUEST {
  type: typeof ADD_SEARCH_REQUIREMENT_REQUEST;
}

interface IADD_SEARCH_REQUIREMENT_SUCCESS {
  type: typeof ADD_SEARCH_REQUIREMENT_SUCCESS;
  data: any;
}

interface IADD_SEARCH_REQUIREMENT_FAILURE {
  type: typeof ADD_SEARCH_REQUIREMENT_FAILURE;
  error: any;
}

export type SearchRequirementActionType =
  | ILOADSEARCH_REQUIREMENT_REQUEST
  | ILOADSEARCH_REQUIREMENT_SUCCESS
  | ILOADSEARCH_REQUIREMENT_FAILURE
  | IADD_SEARCH_REQUIREMENT_REQUEST
  | IADD_SEARCH_REQUIREMENT_SUCCESS
  | IADD_SEARCH_REQUIREMENT_FAILURE;
